version: '3.8'

services:
  target-router:
    image: wbitt/network-multitool
    container_name: test-router
    environment:
      - SSH_PASSWORD=admin
      - HTTP_PORT=80
      - HTTPS_PORT=443
    ports:
      # host:container
      - "2222:22"    # SSH
      - "2323:23"    # Telnet
      - "8080:80"    # HTTP
      - "8443:443"   # HTTPS
      - "161:161/udp" # SNMP
      - "69:69/udp"   # TFTP
    networks:
      - lab_network

networks:
  lab_network:
    driver: bridge